Added new endpoint login and JWT to confirm users
Dima23-ops5/StringBootIntro pull request #11
Opened 2024-07-13 10:11 UTC by Dima23-ops5

2024-07-13 16:36 UTC, MentorMateAcademy requested changes

2024-07-13 16:36 UTC, MentorMateAcademy commented on src/main/java/mate/academy/springbootintro/config/OpenApiConfig.java
> +                .addSecurityItem(new SecurityRequirement().addList("BearerAuth"));
Let`s save it to constants

2024-07-13 16:36 UTC, MentorMateAcademy commented on src/main/java/mate/academy/springbootintro/config/SecurityConfig.java
> +import  static org.springframework.security.config.Customizer.withDefaults;
```suggestion
import static org.springframework.security.config.Customizer.withDefaults;
```

2024-07-13 16:36 UTC, MentorMateAcademy commented on src/main/java/mate/academy/springbootintro/config/SecurityConfig.java
> +import  static org.springframework.security.config.Customizer.withDefaults;
import formatting

2024-07-13 16:36 UTC, MentorMateAcademy commented on src/main/java/mate/academy/springbootintro/security/JwtAuthenticationFilter.java
> +
```suggestion
```

2024-07-13 16:36 UTC, MentorMateAcademy commented on src/main/java/mate/academy/springbootintro/security/JwtAuthenticationFilter.java
> +    protected void doFilterInternal(
```suggestion
    private final CustomUserDetailsService userDetailsService;
    
    @Override
    protected void doFilterInternal(
```

2024-07-13 16:36 UTC, MentorMateAcademy commented on src/main/java/mate/academy/springbootintro/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
save to constants

2024-07-14 10:58 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2024-07-14 10:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/config/SecurityConfig.java
> +import  static org.springframework.security.config.Customizer.withDefaults;
not fixed

2024-07-14 10:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/exeption/LoginException.java
> +public class LoginException extends RuntimeException {
You don't use this exception, remove it

2024-07-14 10:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader(AUTHORIZATION);
Use Spring constant
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-07-14 10:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/security/JwtAuthenticationFilter.java
> +    private static final String AUTHORIZATION = "Authorization";
```suggestion
```

2024-07-14 10:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/security/JwtAuthenticationFilter.java
> +    private static final String BEARER = "Bearer";
```suggestion
    private static final String TOKEN_HEADER = "Bearer ";
```

2024-07-14 10:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/security/JwtAuthenticationFilter.java
> +    private static final int DEFAULT_CAPACITY = 7;
```suggestion
```

See comment below

2024-07-14 10:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(DEFAULT_CAPACITY);
```suggestion
            return bearerToken.substring(TOKEN_HEADER.length());
```

2024-07-14 14:18 UTC, sarakhmen approved these changes

2024-07-16 19:27 UTC, closed without merging