added new enteties shopping cart and item cart, also create new contr…
Dima23-ops5/StringBootIntro pull request #14
Opened 2024-07-16 19:26 UTC by Dima23-ops5

…oller

2024-07-17 12:35 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/controller/ShoppingCartController.java
> +    public ShoppingCardDto getShoppingCard() {
```suggestion
    public ShoppingCardDto getShoppingCard(Authentication authentication) {
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/controller/ShoppingCartController.java
> +        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
```suggestion
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/controller/ShoppingCartController.java
> +    private Long getCurrentUserId() {
```suggestion
    private Long getCurrentUserId(Authentication authentication) {
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/controller/ShoppingCartController.java
> +    public ShoppingCardDto getShoppingCard() {
same for other endpoints

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/dto/cartitem/CreateCartItemRequestDto.java
> +        @NotBlank @Positive Long bookId,
NotBlank is used only for String
```suggestion
        @NotNull @Positive Long bookId,
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/dto/cartitem/CreateCartItemRequestDto.java
> +        @NotBlank int quantity
```suggestion
        @NotNull @Positive int quantity
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/dto/cartitem/UpdateCartItemRequestDto.java
> +        @NotBlank @Positive int quantity
```suggestion
        @NotNull @Positive int quantity
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/model/CartItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/model/CartItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart")
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findByShoppingCartAndBook(
```suggestion
        shoppingCart.getCartItems().stream()
                .filter(item -> item.getBook().getId().equals(cartItemRequestDto.bookId()))
                .findFirst()
                .ifPresentOrElse(item -> item.setQuantity(item.getQuantity() + cartItemRequestDto.quantity()),
                        () -> addCartItemToCart(cartItemRequestDto, book, cart));
        shoppingCartRepository.save(shoppingCart);
        return shoppingCardMapper.toDto(shoppingCart);
```

Where
```
private void addCartItemToCart(CartItemRequestDto itemDto, Book book, ShoppingCart cart) {
        CartItem cartItem = itemMapper.toCartItem(itemDto);
        cartItem.setBook(book);
        cart.addItemToCart(cartItem);
    }
```

Where in ShoppingCart
```
public void addItemToCart(CartItem cartItem) {
        cartItem.setShoppingCart(this);
        cartItems.add(cartItem);
    }
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/dto/shoppingcartdto/ShoppingCardDto.java
> +public record ShoppingCardDto(
```suggestion
public record ShoppingCartDto(
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/mapper/ShoppingCardMapper.java
> +public interface ShoppingCardMapper {
```suggestion
public interface ShoppingCartMapper {
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(
Suggestion

```suggestion
        ShoppingCart cart = repository.findByUserId(userId);
        CartItem cartItem = itemRepository.findByIdAndShoppingCartId(cartItemId, cart.getId())
                .map(item -> {
                    item.setQuantity(itemDto.quantity());
                    return item;
                }).orElseThrow(() -> new EntityNotFoundException(
                        String.format("No cart item with id: %d for user: %d", cartItemId, userId)
                ));
        itemRepository.save(cartItem);
        return cartMapper.toDto(cart);
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(
```suggestion
        ShoppingCart shoppingCart = repository.findByUserId(userId);
        CartItem cartItem = cartItemRepository.findByIdAndShoppingCartId(
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/repository/cartitem/CartItemRepository.java
> +    Optional<CartItem> findByShoppingCartAndBook(ShoppingCart shoppingCart, Book book);
```suggestion
    Optional<CartItem> findByIdAndShoppingCartId(Long itemId, Long cartId);
```

2024-07-17 12:35 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/repository/shoppingcart/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findByUserId(Long userId);
```suggestion
    @EntityGraph(attributePaths = {"cartItems", "cartItems.book"})
    ShoppingCart findByUserId(Long userId);
```

2024-07-19 08:09 UTC, Elena-Bruyako requested changes
Fix previous comments. If you have some questions, please ask in chat

2024-07-19 08:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/controller/BookController.java
> +    @PreAuthorize(value = "hasRole('USER')")
```suggestion
    @PreAuthorize("hasRole('USER')")
```

check other places

2024-07-19 08:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/controller/ShoppingCartController.java
> +        authentication = SecurityContextHolder.getContext().getAuthentication();
```suggestion
```

2024-07-19 08:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/controller/ShoppingCartController.java
> +@RestController
```suggestion
@RestController
@Validated
```

2024-07-19 08:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/dto/shoppingcartdto/ShoppingCardDto.java
> +public record ShoppingCardDto(
Not fixed

2024-07-19 08:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/mapper/ShoppingCardMapper.java
> +public interface ShoppingCardMapper {
Not fixed

2024-07-19 08:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/model/CartItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
not fixed

2024-07-19 08:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/model/CartItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
not fixed

2024-07-19 08:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart")
not fixed

2024-07-19 08:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/repository/cartitem/CartItemRepository.java
> +    Optional<CartItem> findByShoppingCartAndBook(ShoppingCart shoppingCart, Book book);
not fixed

2024-07-19 08:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/repository/shoppingcart/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findByUserId(Long userId);
not fixed

2024-07-19 08:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +                        .orElseThrow(
reformat your style, it's hard to read your code (all places)

2024-07-19 08:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findByShoppingCartAndBook(
not fixed

2024-07-20 12:07 UTC, okuzan requested changes

2024-07-20 12:07 UTC, okuzan commented on src/main/java/mate/academy/springbootintro/controller/ShoppingCartController.java
> +    public ShoppingCartDto getShoppingCard(Authentication authentication) {
```suggestion
    public ShoppingCartDto getShoppingCart(Authentication authentication) {
```

2024-07-20 12:07 UTC, okuzan commented on src/main/java/mate/academy/springbootintro/dto/cartitem/CreateCartItemRequestDto.java
> +        @NotNull int quantity
```suggestion
        @Positive int quantity
```

2024-07-20 12:07 UTC, okuzan commented on src/main/java/mate/academy/springbootintro/dto/cartitem/UpdateCartItemRequestDto.java
> +        @NotNull @Positive int quantity
```suggestion
          @Positive int quantity
```
primitive can't be null

2024-07-22 14:58 UTC, Elena-Bruyako requested changes
see comments

2024-07-22 14:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/controller/ShoppingCartController.java
> +@RestController
`@Positive Long id` annotation won't work without `@Validated`

2024-07-22 14:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootintro/controller/ShoppingCartController.java
> +        authentication = SecurityContextHolder.getContext().getAuthentication();
Why you need this ?
`authentication = SecurityContextHolder.getContext().getAuthentication();`

2024-07-23 09:24 UTC, Elena-Bruyako approved these changes
Well done

2024-08-07 09:15 UTC, closed without merging