Testsforproject
Dima23-ops5/StringBootIntro pull request #19
Opened 2024-08-23 16:02 UTC by Dima23-ops5

2024-08-28 12:31 UTC, Elena-Bruyako requested changes
see comments

check all test according to the comments (pay attention to naming)

2024-08-28 12:31 UTC, Elena-Bruyako commented on src/test/java/mate/academy/springbootintro/controllers/BookControllerTest.java
> +        BookDto book1 = new BookDto();
don't use numbers for naming

2024-08-28 12:31 UTC, Elena-Bruyako commented on src/test/java/mate/academy/springbootintro/controllers/BookControllerTest.java
> +    }
add not valid cases

2024-08-28 12:31 UTC, Elena-Bruyako commented on src/test/java/mate/academy/springbootintro/controllers/CategoryControllerTest.java
> +    }
same here

2024-08-28 12:31 UTC, Elena-Bruyako commented on src/test/java/mate/academy/springbootintro/service/BookServiceImplTest.java
> +
```suggestion
```

2024-08-28 12:31 UTC, Elena-Bruyako commented on src/test/java/mate/academy/springbootintro/service/BookServiceImplTest.java
> +        Mockito.when(bookMapper.toDto(book)).thenReturn(bookDto);
use static imports

2024-08-28 12:31 UTC, Elena-Bruyako commented on src/test/java/mate/academy/springbootintro/service/BookServiceImplTest.java
> +
```suggestion
```

2024-08-28 12:31 UTC, Elena-Bruyako commented on src/test/java/mate/academy/springbootintro/service/BookServiceImplTest.java
> +    public void getBook_GetBookById_False() {
```suggestion
    public void getBook_GetBookByNotValidId_NotOk) {
```

2024-08-28 12:31 UTC, Elena-Bruyako commented on src/test/java/mate/academy/springbootintro/service/BookServiceImplTest.java
> +    public void getBook_GetBookById_False() {
or findById_WithInvalidId_ShouldThrowException

2024-08-29 18:45 UTC, okuzan requested changes
![image](https://github.com/user-attachments/assets/b743f98a-9b81-40db-92b4-bf1622d91d75)
application misspelled

2024-08-29 18:45 UTC, okuzan commented on coverage-error.log
> +[2024.08.23 10:13:22] (Coverage ERROR): Failed to parse agent arguments
why is this file here?

2024-08-30 09:08 UTC, Elena-Bruyako approved these changes

2024-09-17 18:47 UTC, closed without merging