added new methods in controller and used spring jpa
Dima23-ops5/StringBootIntro pull request #3
Opened 2024-06-22 15:41 UTC by Dima23-ops5

2024-06-23 05:40 UTC, Elena-Bruyako requested changes
Did you call your endpoints to get result?

2024-06-23 05:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/model/Book.java
> +    private boolean is_delete = false;
```suggestion
    private boolean isDeleted = false;
```

2024-06-23 05:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/model/Book.java
> +@SQLRestriction(value = "is_delete=false")
```suggestion
@SQLRestriction(value = "is_deleted=false")
```

2024-06-23 05:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/model/Book.java
> +@SQLDelete(sql = "UPDATE books SET is_delete = true WHERE id=?")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = true WHERE id=?")
```

2024-06-23 05:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/service/BookService.java
> +    BookDto deleteBookById(Long id);
```suggestion
    void deleteBookById(Long id);
```

2024-06-23 05:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/service/impl/BookServiceImpl.java
> +                .getById(id));
`getById` is deprecated, use `findById`

2024-06-23 05:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/service/impl/BookServiceImpl.java
>          return bookMapper.toDto(bookRepository
```suggestion
        return bookRepository.findById(id)
                .map(bookMapper::toDto)
                .orElseThrow(() -> new EntityNotFoundException(....
```

2024-06-23 05:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/service/impl/BookServiceImpl.java
> +        Book book = bookRepository.findById(id)
Where is a logic of udpating book?

2024-06-23 05:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/service/impl/BookServiceImpl.java
> +                .orElseThrow(() -> new NoSuchElementException("Cannot find user with id: "
```suggestion
                .orElseThrow(() -> new EntityNotFoundException(....
```

Wrong message

2024-06-23 05:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/service/impl/BookServiceImpl.java
> +    public BookDto deleteBookById(Long id) {
```suggestion
    public void deleteBookById(Long id) {
        bookRepository.deleteById(id);
    }
```

2024-06-23 05:40 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                  name: coverImage
```suggestion
                  name: cover_image
```

2024-06-23 05:40 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                  name: is_delete
```suggestion
                  name: is_deleted
```

2024-06-25 14:38 UTC, Vasul-Pankiv requested changes

2024-06-25 14:38 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/StringBootIntro/mapper/BookMapper.java
> +    void updateBookFromDto(@MappingTarget Book book, CreateBookRequestDto createBookRequestDto);
delete it

2024-06-25 14:38 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/StringBootIntro/service/impl/BookServiceImpl.java
> +        bookMapper.updateBookFromDto(book, createBookRequestDto);
use repository to update book

2024-06-25 14:38 UTC, Vasul-Pankiv commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                    nullable: false
add empty line to the end of file

2024-06-25 14:38 UTC, Vasul-Pankiv commented on src/main/resources/liqubase.properties
> +changelog-file=classpath:db/changelog/db.changelog-master.yaml
same

2024-06-26 10:53 UTC, sarakhmen requested changes
let's improve your solution :)

2024-06-26 10:53 UTC, sarakhmen commented on src/main/java/mate/academy/StringBootIntro/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(book);
why don't you save your book after updating its fields?

2024-06-26 10:53 UTC, sarakhmen commented on src/main/java/mate/academy/StringBootIntro/model/Book.java
> +@SQLRestriction(value = "isDeleted=false")
your column name is 'is_deleted'

2024-06-26 10:53 UTC, sarakhmen commented on src/main/java/mate/academy/StringBootIntro/mapper/BookMapper.java
> +   }
style issue. Please fix such issue in all files

2024-06-27 06:19 UTC, Elena-Bruyako requested changes
Let's fix some comments

2024-06-27 06:19 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/controller/BookController.java
> +                                  @RequestBody CreateBookRequestDto createBookRequestDto) {
```suggestion
                                  @RequestBody @Valid CreateBookRequestDto createBookRequestDto) {
```

2024-06-27 06:19 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/controller/BookController.java
> +
```suggestion
```

2024-06-27 06:19 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/model/Book.java
> +    @Column(name = "cover_image")
```suggestion
```
Hibernate automatically generate column in snake_case style

2024-06-27 06:19 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/service/impl/BookServiceImpl.java
> +                .orElseThrow(EntityNotFoundException::new));
Add informative message

2024-06-27 06:19 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/service/impl/BookServiceImpl.java
> +                .orElseThrow(EntityNotFoundException::new);
the same

2024-06-27 06:19 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/service/impl/BookServiceImpl.java
> +       book.setPrice(createBookRequestDto.getPrice());
use Mapper to update book

2024-06-27 06:19 UTC, Elena-Bruyako commented on src/main/java/mate/academy/StringBootIntro/service/impl/BookServiceImpl.java
> +    public void deleteBookById(Long id) {
```suggestion
    public void deleteBookById(Long id) {
        bookRepository.deleteById(id);
    }
```

2024-06-27 15:49 UTC, closed without merging